---
title: "Prediction Player Stats"
output: pdf_document
date: "2023-09-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages("tidyverse", type = "binary")
install.packages("ggrepel", type = "binary")
install.packages("nflreadr", type = "binary")
install.packages("nflplotR", type = "binary")
```

```{r}
library(tidyverse)
library(ggrepel)
library(nflreadr)
library(nflplotR)
```

```{r}
options(scipen = 9999)
```

```{r}
#https://github.com/nflverse/nflverse-data/releases
#Positions dataframes found on here

positions_2023 = read.csv('/Users/nickcalvaresi/Downloads/roster_weekly_2023.csv')
positions_2022 = read.csv('/Users/nickcalvaresi/Downloads/roster_weekly_2022.csv')
positions_2021 = read.csv('/Users/nickcalvaresi/Downloads/roster_weekly_2021.csv')
positions_2020 = read.csv('/Users/nickcalvaresi/Downloads/roster_weekly_2020.csv')

positions <- rbind(positions_2023, positions_2022, positions_2021, positions_2020) %>%
  mutate(player_id = gsis_id) %>%
  select(player_id, position, full_name) %>%
  filter(position %in% c("QB", "RB", "WR", "TE")) %>%
  distinct() %>%
  separate(full_name, into = c("first_name", "last_name"), sep = " ", remove = FALSE)

```

## Train Set

```{r}
# Load play-by-play data for the specified years
pbp_train <- load_pbp(2020:2022)
```


```{r}
# Create a dataset for type of plays (runs and passes) per game and team
type_of_plays_train <- pbp_train %>%
  group_by(game_id, posteam) %>%
  summarize(runs = sum(rush), passes = sum(pass)) %>%
  filter(!is.na(posteam))
  
```

```{r}
# Create a dataset for receiving statistics
receiving_dataset_train <- pbp_train %>%
  filter(pass == 1) %>%
  group_by(receiver_player_id, receiver_player_name, game_id, posteam ) %>%
  mutate(yards_after_catch = ifelse(is.na(yards_after_catch), 0, yards_after_catch)) %>%
  summarize(aDot = mean(air_yards), yac_rec = sum(yards_after_catch), receiving_yards = sum(yards_gained), incompletions = sum(incomplete_pass), catches = sum(complete_pass), targets = (incompletions + catches), touchdowns = sum(touchdown), fumbles = sum(fumble), avg_rec_epa = mean(epa)) %>%
  ungroup()
  

```



```{r}
# Merge receiving and type_of_plays datasets
receiving_merged_train <- merge(x = receiving_dataset_train, y = type_of_plays_train, all.x = TRUE) %>%
  filter(!is.na(receiver_player_id)) %>%
  mutate(target_share = targets/passes) %>%
  mutate(player_id = receiver_player_id, player_name = receiver_player_name) %>%
  select(game_id, player_id, player_name, posteam, aDot, yac_rec, receiving_yards, catches, targets, target_share, touchdowns, fumbles, avg_rec_epa)
```

```{r}
# Create a dataset for rushing statistics
rushing_dataset_train <- pbp_train %>%
  filter(rush == 1) %>%
  group_by(rusher_player_id, rusher_player_name, game_id, posteam ) %>%
  summarize(rushes = sum(rush), rush_yards = sum(yards_gained), touchdowns = sum(touchdown), player_id = rusher_player_id, player_name =  rusher_player_name, fumbles = sum(fumble), avg_rush_epa = mean(epa)) %>%
  ungroup() %>%
  select(game_id, player_id, player_name, posteam, rushes, rush_yards, touchdowns, fumbles, avg_rush_epa) %>%
  filter(!is.na(player_id)) %>%
  arrange(game_id)
```

```{r}
# Merge rushing and receiving datasets to create a fantasy dataset
fantasy_merged_train <- full_join(x=rushing_dataset_train, y=receiving_merged_train, 
             by=c("game_id", "player_id","player_name", "posteam")) %>%
  distinct() %>%
  mutate(touchdowns = (touchdowns.x + touchdowns.y), fumbles = (fumbles.x + fumbles.y)) %>%
  select(-c(touchdowns.x, touchdowns.y, fumbles.x, fumbles.y)) %>%
  filter(!is.na(player_id)) %>%
  replace(is.na(.), 0)
```



```{r}
# Create a dataset for quarterback statistics
qb_data_train <- pbp_train %>% 
  filter(pass == 1) %>%
  group_by(passer_player_id, passer_player_name, game_id, posteam ) %>%
  summarize(passing_yards = sum(yards_gained), incompletions = sum(incomplete_pass), completions = sum(complete_pass), attempts = (incompletions + completions), passing_touchdowns = sum(touchdown), fumbles = sum(fumble), interceptions = sum(interception), avg_throw_epa = mean(epa)) %>%
  mutate(player_id = passer_player_id, player_name = passer_player_name) %>%
  ungroup() %>%
select(-c(passer_player_id, passer_player_name)) %>%
  select(game_id, player_id, player_name, posteam, passing_yards, incompletions, completions, attempts, passing_touchdowns, fumbles, interceptions, avg_throw_epa)
  
```

```{r}
# Merge quarterback statistics with the fantasy dataset
fantasy_merged_new_train <- full_join(x=fantasy_merged_train,y=qb_data_train, 
             by=c("game_id", "player_id","player_name", "posteam")) %>%
  distinct() %>%
  mutate(fumbles = (fumbles.x + fumbles.y)) %>%
  select(-c(fumbles.x, fumbles.y)) %>%
  filter(!is.na(player_id)) %>%
  replace(is.na(.), 0)
```


```{r}
sapply(fantasy_merged_new, function(x) sum(is.na(x)))  
```



```{r}
# Calculate fantasy points
fantasy_points <- fantasy_merged_new_train %>%
  mutate(fan_points = (.1*rush_yards) + (.1*receiving_yards) + (.5*catches) + (.04*passing_yards) + (4*passing_touchdowns) + (-2*interceptions) + (6*touchdowns) )
```



```{r}
new <- left_join(x = fantasy_points, y = positions, by = "player_id") %>%
  filter(!is.na(position))
```

```{r}
sapply(new, function(x) sum(is.na(x)))  
```


```{r}

# Assuming df is your DataFrame
ggplot(avg_new, aes(x = avg_fan_points, fill = position)) +
  geom_density(alpha = 0.5) +
  labs(title = "Density Plot of Average Fantasy Points by Position through Weeks 1-3 ",
       x = "Average Fantasy Points",
       y = "Density") +
  theme_minimal()


```


```{r}


```



